//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drive()
        {
            this.Travels = new HashSet<Travels>();
        }
    
        public int DriveId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public string OriginCity { get; set; }
        public string OriginStreet { get; set; }
        public string OriginNumBuild { get; set; }
        public string OriginArea { get; set; }
        public string DestenitationCity { get; set; }
        public string DestenitationStreet { get; set; }
        public string DestenitationNumBuild { get; set; }
        public string DestenitationArea { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.TimeSpan> ExitTime { get; set; }
        public Nullable<System.TimeSpan> ArrivedTime { get; set; }
        public string PackageType { get; set; }
        public string Remarks { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travels> Travels { get; set; }
    }
}
