//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDasiSariEntities1 : DbContext
    {
        public ProjectDasiSariEntities1()
            : base("name=ProjectDasiSariEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drive> Drive { get; set; }
        public virtual DbSet<Packages> Packages { get; set; }
        public virtual DbSet<Travels> Travels { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
